package com.example.dailyfocus.core.designsystem.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2D5BFF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDDE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001453)
val md_theme_light_secondary = Color(0xFF565E71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_tertiary = Color(0xFF006C4C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFFBF8FD)
val md_theme_light_onBackground = Color(0xFF191B1F)
val md_theme_light_surface = Color(0xFFFBF8FD)
val md_theme_light_onSurface = Color(0xFF191B1F)
val md_theme_light_surfaceVariant = Color(0xFFE2E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44464F)
val md_theme_light_surfaceContainer = Color(0xFFF0EDF3)
val md_theme_light_surfaceContainerHigh = Color(0xFFEAE7ED)
val md_theme_light_outline = Color(0xFF757780)
val md_theme_light_error = Color(0xFFBA1A1A)

// Dark Theme Tokens (OLED-friendly dark greys)
val md_theme_dark_primary = Color(0xFFA8C7FA)
val md_theme_dark_onPrimary = Color(0xFF002773)
val md_theme_dark_primaryContainer = Color(0xFF0C3FAF)
val md_theme_dark_onPrimaryContainer = Color(0xFFDDE1FF)
val md_theme_dark_secondary = Color(0xFFBEC6DC)
val md_theme_dark_onSecondary = Color(0xFF283041)
val md_theme_dark_tertiary = Color(0xFF70D8A5)
val md_theme_dark_onTertiary = Color(0xFF003825)
val md_theme_dark_background = Color(0xFF111318)
val md_theme_dark_onBackground = Color(0xFFE2E2E8)
val md_theme_dark_surface = Color(0xFF111318)
val md_theme_dark_onSurface = Color(0xFFE2E2E8)
val md_theme_dark_surfaceVariant = Color(0xFF44464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_surfaceContainer = Color(0xFF1D2024)
val md_theme_dark_surfaceContainerHigh = Color(0xFF282A2F)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_error = Color(0xFFFFB4AB)